version: '2'
services:
  app:
    image: jeboehm/nextcloud:latest
    build: .
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    # nginx-proxy uses these variables to autoconfigure the nextcloud vhost.
    environment:
      VIRTUAL_HOST: nextcloud.local
      LETSENCRYPT_HOST: nextcloud.local
      LETSENCRYPT_EMAIL: jeff@example.com
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: "db"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud

  # This is only an example.
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  nextcloud:
